print("Hello World!")
print(1+1)
print([])
print([1,2,3])
print([1, 2, 3][0])
print([1, 2, 3][1])
print("Nova linha!")
print("Nova linha 2!")
print("Nova linha 3!")
print("Nova linha 4!")
print("Nova linha 5!")
print("Nova linha 6!")
print("Nova linha 7!")
